Update targets and runtime budgets.
mlcommons/algorithmic-efficiency pull request #402
Opened 2023-06-09 11:16 UTC by fsschneider

This PR updates the (test) targets and maximum runtime budgets according to Table 7 of the AlgoPerf paper.

2023-06-09 18:53 UTC, priyakasimbeg requested changes
From the latest pytorch measurements it seems like some of the pytorch workloads are slower than some of the jax workloads. 
Do we want to set the maximum runtime to the maximum extrapolated time between the two frameworks? If so we'd want to increase criteo to ~3.5 hours, ogbg to 6.5 hours, and wmt to ~16 hours.
For reference the exact numbers are here in the [Time Comparison Jax vs Pytorch (deepspeech fix) tab](https://docs.google.com/spreadsheets/d/1PGuF-e_hux5pYHFawr0Q62mDzGNiNX3FuvlsN2MbsOQ/edit?resourcekey=0-Onr8x3KwAuXIWEcocaqKnQ#gid=804216215).
In any case we have updated deepspeech numbers ready too so we can integrate those in this PR to ~17 hours.

2023-06-10 04:14 UTC, georgedahl commented
I believe we decided in one of the working group meetings to just use the jax-derived time budgets.

2023-06-14 03:13 UTC, znado approved these changes

2023-06-14 23:40 UTC, priyakasimbeg approved these changes
As discussed in working group meeting, we'll stick to the jax times to set the maximum runtimes.

2023-06-15 18:27 UTC, merged