Fix `_get_time`
mlcommons/algorithmic-efficiency pull request #430
Opened 2023-07-06 17:43 UTC by runame

Unless I'm missing something we always need to call `torch.cuda.synchronize()` for timing, not only when DDP is used. Also, I think this shouldn't have unwanted side-effects for the Jax runs.

2023-07-06 18:08 UTC, priyakasimbeg approved these changes

2023-07-06 18:52 UTC, priyakasimbeg commented
Just noticed the baseline tests on CPU fail, because torch.cuda throws an error when run in CPU mode?
Can we check if we're using the GPU (for both pytorch and jax) before calling synchronize?

2023-07-06 18:54 UTC, priyakasimbeg requested changes
Baseline tests on CPU fail when calling torch.cuda.synchronize. I think we should add a check whether we're running on cpu before calling torch.cuda.synchronize. Also torch may not be installed if submitters are using just jax framework, so we should add a check for the framework as well.

2023-07-07 11:25 UTC, runame commented
Sorry, fixed! `torch` should always be installed, even when someone only wants to run `jax` workloads.

2023-07-11 02:07 UTC, priyakasimbeg approved these changes
LGTM! Thanks for the fix!

2023-07-12 17:20 UTC, znado approved these changes

2023-07-12 17:20 UTC, merged