Cleanup, fixes, and tests
mlcommons/algorithmic-efficiency pull request #71
Opened 2022-04-13 19:06 UTC by znado

Still a few loose ends to wrap up but ready for a first review.

Refactoring evals to use `eval_model()` in the root abstract class in `spec.py`, and have all workloads define `_eval_model_on_split()`. This will also make it so that metrics returned by `eval_model()` have the dataset split prepended to them with a `/`, so for examples `eval_train/accuracy`.

Adding `tests/reference_submission_tests.py`. This is a brief test that runs the for the workload and reference submission code for one train and one eval step for all workloads, without the real data iterator because it is not realistic to have all datasets available at testing time.

Adding an end-to-end test using MNIST to `submission_runner_test.py`.

Making both MNIST versions feature complete.

Cleaning up some WMT and other workloads.

2022-04-19 12:28 UTC, fsschneider requested changes
Overall LGTM! Thanks for the great PR which does a lot of important and great cleaning up.

I just had some minor comments and questions.

Two more things that I wanted to mention that didn't fit as inline comments:

1. Could you fix the `README.md` so that under `Running a workload` it uses the correct paths? I think the only changes needed are changing `python3 algorithmic_efficiency/submission_runner.py` to `python3 submission_runner.py` for both JAX and PyTorch. I did this in PR #65 but I will close this one as it is superseded by yours.
2. Could you make sure that the PR passes all the Github Actions, e.g. linting and testing?

Thanks again for this great PR!

2022-04-19 12:28 UTC, fsschneider commented on algorithmic_efficiency/workloads/mnist/workload.py
> +    return 10000
I may be mistaken here, but I think currently, we are using `num_eval_train_examples = num_train_examples = 50000`, not `10000`, no?
Judging from:

https://github.com/znado/algorithmic-efficiency/blob/17fc48fd0062289f05c9eb62d1d45f72e5837d08/algorithmic_efficiency/workloads/mnist/mnist_pytorch/workload.py#L62-L63

we are using the same dataset for both `train` and `train_eval`.

If I didn't make a mistake, the same would be true for the `ImageNet` workload as well.

2022-04-19 12:28 UTC, fsschneider commented on algorithmic_efficiency/workloads/ogbg/ogbg_jax/workload.py
> +    # DO NOT SUBMIT use num_examples
Same questions as above.

2022-04-19 12:28 UTC, fsschneider commented on algorithmic_efficiency/workloads/wmt/wmt_jax/workload.py
> +        predict_ds=self._predict_ds, # DO NOT SUBMIT delete
Is this comment still relevant?

2022-04-20 01:02 UTC, znado commented on algorithmic_efficiency/spec.py
> +    # Evaluate on the test set if we have one.
Maybe? I think we should figure out what to do for validation sets for all workloads, added it to the meeting agenda for this week.

2022-04-20 01:08 UTC, znado commented on algorithmic_efficiency/workloads/imagenet/imagenet_pytorch/workload.py
> +    # DO NOT SUBMIT use num_examples
going to dismiss for now until we figure out any imagenet validation sets.

2022-04-20 01:15 UTC, znado commented on algorithmic_efficiency/workloads/ogbg/ogbg_jax/workload.py
> +    # DO NOT SUBMIT use num_examples
fixed

2022-04-20 01:23 UTC, znado commented on algorithmic_efficiency/spec.py
> +    # DO NOT SUBMIT handle the case where batch size > num examples or when num_examples % batch_size != 0
yeah I think this is probably fine then, I just added this defensively to make sure I didn't leave it unchecked (I meant to follow up on it before sending the PR). thanks for checking!

2022-04-20 09:12 UTC, fsschneider approved these changes

2022-04-20 09:12 UTC, merged

2022-05-02 18:35 UTC, runame commented
@znado When trying to merge the changes from this PR into my `wmt-pytorch` branch, I noticed that it seems to break the WMT Jax workload: you have [changed](https://github.com/mlcommons/algorithmic-efficiency/blob/main/algorithmic_efficiency/workloads/wmt/wmt_jax/input_pipeline.py#L257-L265) the `get_wmt_datasets()` function to `get_wmt_dataset()` in the input pipeline, but in the workload the `build_input_queue()` function is [not adjusted accordingly](https://github.com/mlcommons/algorithmic-efficiency/blob/main/algorithmic_efficiency/workloads/wmt/wmt_jax/workload.py#L308). I assume you want to call `build_input_queue()` for each dataset separately in the workload?

2022-05-02 20:44 UTC, znado commented
> @znado When trying to merge the changes from this PR into my `wmt-pytorch` branch, I noticed that it seems to break the WMT Jax workload: you have [changed](https://github.com/mlcommons/algorithmic-efficiency/blob/main/algorithmic_efficiency/workloads/wmt/wmt_jax/input_pipeline.py#L257-L265) the `get_wmt_datasets()` function to `get_wmt_dataset()` in the input pipeline, but in the workload the `build_input_queue()` function is [not adjusted accordingly](https://github.com/mlcommons/algorithmic-efficiency/blob/main/algorithmic_efficiency/workloads/wmt/wmt_jax/workload.py#L308). I assume you want to call `build_input_queue()` for each dataset separately in the workload?

Ah yes, at the last minute I reverted some of the WMT changes to make in a more comprehensive follow-up PR, but must have only partially reverted them. Thanks for catching that, you're totally right. Feel free to revert/refactor anything as needed to get it running again, and I'll hopefully have the other PR(s) that continue cleaning stuff up done soon.

2022-05-02 20:49 UTC, runame commented
> Ah yes, at the last minute I reverted some of the WMT changes to make in a more comprehensive follow-up PR, but must have only partially reverted them. Thanks for catching that, you're totally right. Feel free to revert/refactor anything as needed to get it running again, and I'll hopefully have the other PR(s) that continue cleaning stuff up done soon.

Thanks for the quick reply! I will just adjust the workload to the new `get_wmt_datasets()` function for now.